// ... imports
import { Plus, FileSpreadsheet, Database, Search, Pencil, Trash2, ChevronLeft, ChevronRight, X, Truck, BookUser } from 'lucide-react';

type Tab = 'items' | 'machines' | 'recipes' | 'partners' | 'vehicles' | 'customers';

export default function DataManagement() {
    const [activeTab, setActiveTab] = useState<Tab>('items');
    // ... states

    // 1. DATA FETCHING
    const fetchData = async () => {
        setLoading(true);
        setExistingData([]);

        try {
            let query;
            if (activeTab === 'machines') {
                query = supabase.from('sys_machines_v2').select('*').order('machine_id');
            } else if (activeTab === 'items') {
                query = supabase.from('master_items_v2').select('*').order('sku').limit(100);
            } else if (activeTab === 'partners') {
                query = supabase.from('crm_partners_v2').select('*').order('partner_id').limit(100);
            } else if (activeTab === 'recipes') {
                query = supabase.from('bom_headers_v2').select('*, bom_items_v2(*)').order('created_at', { ascending: false }).limit(50);
            } else if (activeTab === 'vehicles') {
                query = supabase.from('sys_vehicles').select('*').order('id');
            } else if (activeTab === 'customers') {
                query = supabase.from('sys_customers').select('*').order('name').limit(100);
            }

            if (query) {
                const { data, error } = await query;
                if (error) throw error;
                if (data) setExistingData(data);
            }
        } catch (err: any) {
            addToLog(`❌ Fetch Error: ${err.message}`);
        } finally {
            setLoading(false);
        }
    };

    // ... useEffect ...

    // 2. FORM & ACTIONS
    const handleDelete = async (id: string) => {
        if (!window.confirm(`Are you sure you want to delete record ${id}?`)) return;

        let table = '';
        let idField = '';

        if (activeTab === 'items') { table = 'master_items_v2'; idField = 'sku'; }
        else if (activeTab === 'machines') { table = 'sys_machines_v2'; idField = 'machine_id'; }
        else if (activeTab === 'partners') { table = 'crm_partners_v2'; idField = 'partner_id'; }
        else if (activeTab === 'vehicles') { table = 'sys_vehicles'; idField = 'id'; }
        else if (activeTab === 'customers') { table = 'sys_customers'; idField = 'id'; }
        else { addToLog("⚠️ Deletion not supported for this type yet."); return; }

        try {
            const { error } = await supabase.from(table).delete().eq(idField, id);
            if (error) throw error;
            addToLog(`✅ Deleted ${id}`);
            fetchData();
        } catch (err: any) {
            addToLog(`❌ Delete Error: ${err.message}`);
        }
    };

    const handleSave = async () => {
        // ... (importing state)
        // Determine table and PK
        let table = '';
        let pk = '';
        let data = { ...singleForm };

        if (activeTab === 'items') { table = 'master_items_v2'; pk = 'sku'; }
        else if (activeTab === 'machines') { table = 'sys_machines_v2'; pk = 'machine_id'; }
        else if (activeTab === 'partners') { table = 'crm_partners_v2'; pk = 'partner_id'; }
        else if (activeTab === 'vehicles') { table = 'sys_vehicles'; pk = 'id'; }
        else if (activeTab === 'customers') { table = 'sys_customers'; pk = 'id'; } // UUID generated by DB if missing, but we handle upsert carefully

        if (!table) return;

        try {
            // Special handling for Customer UUID on Insert
            if (activeTab === 'customers' && !data.id && !editMode) {
                // Delete ID to let DB generate it
                delete data.id;
                pk = 'id'; // Wait, upsert needs a match. For Insert, we use insert().
                const { error } = await supabase.from(table).insert(data);
                if (error) throw error;
            } else {
                if (activeTab !== 'customers' && !data[pk]) throw new Error(`Primary Key (${pk}) is required.`);
                const { error } = await supabase.from(table).upsert(data);
                if (error) throw error;
            }

            addToLog(`✅ ${editMode ? 'Updated' : 'Created'} record`);
            resetForm();
            fetchData();
        } catch (err: any) {
            addToLog(`❌ Save Error: ${err.message}`);
        } finally {
            setImporting(false);
        }
    };

    // ... bulk import logic ...

    // RENDER
    return (
        <div className="p-6 bg-slate-50 min-h-screen">
            {/* ... header ... */}
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
                {/* TABS */}
                <div className="flex border-b bg-gray-50 overflow-x-auto">
                    {(['items', 'machines', 'vehicles', 'customers', 'partners', 'recipes'] as Tab[]).map(t => (
                        <button
                            key={t}
                            onClick={() => { setActiveTab(t); setMode('single'); }}
                            className={`px-6 py-4 font-semibold capitalize transition-colors border-b-2 whitespace-nowrap ${activeTab === t ? 'bg-white text-blue-600 border-blue-600' : 'text-slate-500 border-transparent hover:text-slate-700'
                                }`}
                        >
                            {t}
                        </button>
                    ))}
                </div>

                {/* ... toolbar ... */}

                <div className="p-6">
                    {/* MODE: SINGLE / EDIT */}
                    {mode === 'single' && (
                        <div className="mb-8 bg-slate-50 p-6 rounded-lg border border-slate-200">
                            {/* ... title ... */}
                            <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                                {/* ... existing forms ... */}

                                {activeTab === 'vehicles' && (
                                    <>
                                        <input placeholder="Vehicle ID (e.g. TRUCK-01) *" value={singleForm.id || ''} onChange={e => setSingleForm({ ...singleForm, id: e.target.value })} className="p-2 border rounded" disabled={editMode} />
                                        <input placeholder="Plate Number *" value={singleForm.plate_number || ''} onChange={e => setSingleForm({ ...singleForm, plate_number: e.target.value })} className="p-2 border rounded" />
                                        <select value={singleForm.status || ''} onChange={e => setSingleForm({ ...singleForm, status: e.target.value })} className="p-2 border rounded">
                                            <option value="Available">Available</option>
                                            <option value="On-Route">On-Route</option>
                                            <option value="Maintenance">Maintenance</option>
                                        </select>
                                        <input type="number" placeholder="Max Volume (m³)" value={singleForm.max_volume_m3 || ''} onChange={e => setSingleForm({ ...singleForm, max_volume_m3: e.target.value })} className="p-2 border rounded" />
                                        <input type="number" placeholder="Max Weight (kg)" value={singleForm.max_weight_kg || ''} onChange={e => setSingleForm({ ...singleForm, max_weight_kg: e.target.value })} className="p-2 border rounded" />
                                        <input placeholder="Dimensions (e.g. 20x8x8)" value={singleForm.internal_dims || ''} onChange={e => setSingleForm({ ...singleForm, internal_dims: e.target.value })} className="p-2 border rounded" />
                                    </>
                                )}

                                {activeTab === 'customers' && (
                                    <>
                                        <input placeholder="Customer Name *" value={singleForm.name || ''} onChange={e => setSingleForm({ ...singleForm, name: e.target.value })} className="p-2 border rounded" />
                                        <input placeholder="Zone (North/Central/South)" value={singleForm.zone || ''} onChange={e => setSingleForm({ ...singleForm, zone: e.target.value })} className="p-2 border rounded" />
                                        <input placeholder="Contact Person" value={singleForm.contact_person || ''} onChange={e => setSingleForm({ ...singleForm, contact_person: e.target.value })} className="p-2 border rounded" />
                                        <input placeholder="Phone" value={singleForm.phone || ''} onChange={e => setSingleForm({ ...singleForm, phone: e.target.value })} className="p-2 border rounded" />
                                        <div className="col-span-2">
                                            <input placeholder="Full Address" value={singleForm.address || ''} onChange={e => setSingleForm({ ...singleForm, address: e.target.value })} className="w-full p-2 border rounded" />
                                        </div>
                                        <input placeholder="Lat (e.g. 3.123)" value={singleForm.lat || ''} onChange={e => setSingleForm({ ...singleForm, lat: e.target.value })} className="p-2 border rounded" />
                                        <input placeholder="Lng (e.g. 101.456)" value={singleForm.lng || ''} onChange={e => setSingleForm({ ...singleForm, lng: e.target.value })} className="p-2 border rounded" />
                                    </>
                                )}
                            </div>
                            {/* ... save button ... */}
                        </div>
                    )}

                    {/* ... bulk mode ... */}

                    {/* DATA TABLE */}
                    <div className="relative overflow-x-auto rounded-lg border border-slate-200">
                        <table className="w-full text-sm text-left text-slate-600">
                            <thead className="text-xs text-slate-700 uppercase bg-slate-50">
                                <tr>
                                    {/* ... existing headers ... */}
                                    {activeTab === 'vehicles' && <>
                                        <th className="px-6 py-3">ID</th>
                                        <th className="px-6 py-3">Plate</th>
                                        <th className="px-6 py-3">Status</th>
                                        <th className="px-6 py-3">Capacity</th>
                                    </>}
                                    {activeTab === 'customers' && <>
                                        <th className="px-6 py-3">Name</th>
                                        <th className="px-6 py-3">Zone</th>
                                        <th className="px-6 py-3">Contact</th>
                                        <th className="px-6 py-3">GPS</th>
                                    </>}
                                    <th className="px-6 py-3 text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {loading ? (
                                    <tr><td colSpan={5} className="p-8 text-center">Loading data...</td></tr>
                                ) : displayData.length === 0 ? (
                                    <tr><td colSpan={5} className="p-8 text-center text-slate-400">No records found.</td></tr>
                                ) : (
                                    displayData.map((row, i) => (
                                        <tr key={i} className="bg-white border-b hover:bg-slate-50 transition-colors">
                                            {/* ... existing rows ... */}
                                            {activeTab === 'vehicles' && <>
                                                <td className="px-6 py-4 font-medium text-slate-900">{row.id}</td>
                                                <td className="px-6 py-4">{row.plate_number}</td>
                                                <td className="px-6 py-4"><span className={`px-2 py-1 rounded text-xs ${row.status === 'Available' ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'}`}>{row.status}</span></td>
                                                <td className="px-6 py-4 text-xs">{row.max_volume_m3}m³ / {row.max_weight_kg}kg</td>
                                            </>}
                                            {activeTab === 'customers' && <>
                                                <td className="px-6 py-4 font-medium text-slate-900">{row.name}</td>
                                                <td className="px-6 py-4">{row.zone}</td>
                                                <td className="px-6 py-4">{row.contact_person}</td>
                                                <td className="px-6 py-4 text-xs">{row.lat ? '✅ Set' : '❌ Missing'}</td>
                                            </>}

                                            <td className="px-6 py-4 text-right flex justify-end gap-2">
                                                <button onClick={() => handleEdit(row)} className="p-1 text-blue-600 hover:bg-blue-50 rounded"><Pencil size={16} /></button>
                                                <button onClick={() => handleDelete(row.sku || row.machine_id || row.partner_id || row.recipe_id || row.id)} className="p-1 text-red-600 hover:bg-red-50 rounded"><Trash2 size={16} /></button>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                    {/* ... pagination ... */}
                </div>
            </div>
            {/* ... logs ... */}
        </div>
    );
}

