-- Clear dependent data first to avoid Foreign Key violations
DELETE FROM bom_items_v2;
DELETE FROM bom_headers_v2;
DELETE FROM stock_ledger_v2;
-- DELETE FROM v2_inventory_snapshot; -- Cannot delete from view
-- DELETE FROM sys_production_log_v2; -- Optional: if logs reference items with FK

-- Clear existing data
DELETE FROM master_items_v2;

-- AIRTUBE SERIES (Purchased)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('AIRTUBE-15CM-300METER-7155', 'AIRTUBE-15CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-15CM-50METER', 'AIRTUBE-15CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-20CM-300METER-7135', 'AIRTUBE-20CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-20CM-50METER', 'AIRTUBE-20CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-25CM-300METER-7136', 'AIRTUBE-25CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-25CM-50METER', 'AIRTUBE-25CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-30CM-300METER-7137', 'AIRTUBE-30CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-30CM-50METER', 'AIRTUBE-30CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-35CM-300METER-7138', 'AIRTUBE-35CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-35CM-50METER', 'AIRTUBE-35CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-40CM-300METER-7139', 'AIRTUBE-40CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-40CM-50METER', 'AIRTUBE-40CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-45CM-300METER-7140', 'AIRTUBE-45CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-45CM-50METER', 'AIRTUBE-45CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-50CM-300METER', 'AIRTUBE-50CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-50CM-50METER', 'AIRTUBE-50CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-55CM-300METER-7151', 'AIRTUBE-55CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-55CM-50METER', 'AIRTUBE-55CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-60CM-300METER', 'AIRTUBE-60CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-60CM-50METER', 'AIRTUBE-60CM-50METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-65CM-300METER', 'AIRTUBE-65CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-70CM-300METER', 'AIRTUBE-70CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-75CM-300METER', 'AIRTUBE-75CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active'),
('AIRTUBE-80CM-300METER', 'AIRTUBE-80CM-300METER', 'FG', 'AirTube', 'Purchased', 'Roll', 'Active');

-- AWB SERIES (Trading/Purchased)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('AWB-10000-BOX', 'AIR WAY BILL 10000PCS X1 PER BOX', 'FG', 'AWB', 'Purchased', 'Box', 'Active'),
('AWB-2000-BOX', 'AIR WAY BILL 2000PCS X4 PER BOX', 'FG', 'AWB', 'Purchased', 'Box', 'Active'),
('AWB-2000-STACK', 'AIR WAY BILL 2000PCS PER STACK', 'FG', 'AWB', 'Purchased', 'Unit', 'Active'),
('AWB-350-BOX', 'AIR WAY BILL 350PCS (ROLL) X24 PER BOX', 'FG', 'AWB', 'Purchased', 'Box', 'Active'),
('AWB-350-ROLL', 'AIR WAY BILL 350PCS PER ROLL', 'FG', 'AWB', 'Purchased', 'Roll', 'Active'),
('AWB-5000-BOX', 'AIR WAY BILL 5000PCS X2 PER BOX', 'FG', 'AWB', 'Purchased', 'Box', 'Active'),
('AWB-5000-STACK', 'AIR WAY BILL 5000PCS PER STACK', 'FG', 'AWB', 'Purchased', 'Unit', 'Active'),
('AWB-500-BOX', 'AIR WAY BILL 500PCS X20 PER BOX', 'FG', 'AWB', 'Purchased', 'Box', 'Active'),
('AWB-500-STACK', 'AIR WAY BILL 500PCS PER STACK', 'FG', 'AWB', 'Purchased', 'Unit', 'Active');

-- COURIER BAG (BLACK) (Purchased)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('B-17', 'Courier Bag Black,17X30CM (40rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-20', 'Courier Bag Black,20X30CM (31rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-25', 'Courier Bag Black,25X35CM (23rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-28', 'Courier Bag Black,28X42CM (19rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-32', 'Courier Bag Black,32X45CM (10rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-35', 'Courier Bag Black,35X45CM (10rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-38', 'Courier Bag Black,38X52CM (8rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-40', 'Courier Bag Black,40X55CM (8rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-45', 'Courier Bag Black,45X55CM (10rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-50', 'Courier Bag Black 50X65cm (10rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('B-60', 'Courier Bag Black,60X80CM (6rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active');

-- BABY ROLL & PENS (Purchased/Trading)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('BABYROLL-BLACK', 'Baby Roll Mini Stretch Film 100mm x 250gram (BLACK)', 'FG', 'StretchFilm', 'Purchased', 'Roll', 'Active'),
('BABYROLL-CLEAR', 'Baby Roll Mini Stretch Film 100mm x 250gram (CLEAR)', 'FG', 'StretchFilm', 'Purchased', 'Roll', 'Active'),
('blackpen', 'Black Pen x1', 'FG', 'Trading', 'Purchased', 'Unit', 'Active'),
('bluepen', 'Blue Pen x1', 'FG', 'Trading', 'Purchased', 'Unit', 'Active'),
('redpen', 'Red Pen x1', 'FG', 'Trading', 'Purchased', 'Unit', 'Active'),
('refill-black', 'Pen Refill ( Black ) x1', 'FG', 'Trading', 'Purchased', 'Unit', 'Active'),
('refillblack10', 'Pen Refill ( Black ) x10', 'FG', 'Trading', 'Purchased', 'Unit', 'Active'),
('refill-blue', 'Pen Refill ( Blue ) x1', 'FG', 'Trading', 'Purchased', 'Unit', 'Active'),
('refillblue10', 'Pen Refill ( Blue ) x10', 'FG', 'Trading', 'Purchased', 'Unit', 'Active'),
('refill-red', 'Pen Refill ( Red) x1', 'FG', 'Trading', 'Purchased', 'Unit', 'Active'),
('refillred10', 'Pen Refill ( Red) x10', 'FG', 'Trading', 'Purchased', 'Unit', 'Active');

-- COURIER BAG (COLORS) (Purchased)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('BLUE-L-P', 'Courier Bag Blue(With Pocket),L (32cmx49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('BLUE-M-P', 'Courier Bag Blue(With Pocket),M (26cmx37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('BLUE-S-P', 'Courier Bag Blue(With Pocket),S (18cmx30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('L-BLUE', 'Courier Bag Tiffany Blue,L (32x49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('M-BLUE', 'Courier Bag Tiffany Blue,M (26x37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('S-BLUE', 'Courier Bag Tiffany Blue,S (18x30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('GREEN-17', 'Courier Bag Green,17X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('GREEN-20', 'Courier Bag Green,20X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('GREEN-25', 'Courier Bag Green,25X35CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('GREEN-28', 'Courier Bag Green,28X42CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('GREEN-32', 'Courier Bag Green,32X45CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('GREEN-35', 'Courier Bag Green,35X45CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('GREEN-38', 'Courier Bag Green,38X52CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('L-BOSSKU-GREEN', 'Courier Bag Green(BOSSKU),L (32x49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('M-BOSSKU-GREEN', 'Courier Bag Green(BOSSKU),M (26x37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('S-BOSSKU-GREEN', 'Courier Bag Green(BOSSKU),S (18x30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('XL-GREEN-BOSSKU', 'Courier Bag Green XL 40x56cm', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('L-BOSSKU-YELLOW', 'Courier Bag Yellow(BOSSKU),L (32x49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('M-BOSSKU-YELLOW', 'Courier Bag Yellow(BOSSKU),M (26x37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('S-BOSSKU-YELLOW', 'Courier Bag Yellow(BOSSKU),S (18x30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('L-BROWN', 'Courier Bag Choco Brown,L (32x49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('M-BROWN', 'Courier Bag Choco Brown,M (26x37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('S-BROWN', 'Courier Bag Choco Brown,S (18x30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('L-ENVELOPE', 'L size Envelope (26*32+4cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('M-ENVELOPE', 'M size Envelope (22*28+4cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('S-ENVELOPE', 'S size Envelope (18*23+4cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('XL-ENVELOPE', 'XL size Envelope (30*38+4cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('L-PINK', 'Courier Bag Pink,L (32x49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('M-PINK', 'Courier Bag Pink,M (26x37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('S-PINK', 'Courier Bag Pink,S (18x30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('XL-PINK', 'Courier Bag Pink XL 40x56cm', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PINK-17', 'Courier Bag Pink,17X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PINK-20', 'Courier Bag Pink,20X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PINK-25', 'Courier Bag Pink,25X35CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PINK-28', 'Courier Bag Pink,28X42CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PINK-32', 'Courier Bag Pink,32X45CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PINK-35', 'Courier Bag Pink,35X45CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PINK-38', 'Courier Bag Pink,38X52CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('L-PUR', 'Courier Bag Purple,L (32x49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('M-PUR', 'Courier Bag Purple,M (26x37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('S-PUR', 'Courier Bag Purple,S (18x30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('XL-PUR', 'Courier Bag Purple XL 40x56cm', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-17', 'Courier Bag Purple,17X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-20', 'Courier Bag Purple,20X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-25', 'Courier Bag Purple,25X35CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-28', 'Courier Bag Purple,28X42CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-32', 'Courier Bag Purple,32X45CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-38', 'Courier Bag Purple,38X52CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-L-P', 'Courier Bag Purple (With Pocket),L (32cmx49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-M-P', 'Courier Bag Purple (With Pocket),M (26cmx37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-S-P', 'Courier Bag Purple (With Pocket),S (18cmx30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('PUR-XL-P', 'Courier Bag Purple (With Pocket),XL (40cmx56cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('L-R', 'Courier Bag Red,L (32x49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('M-R', 'Courier Bag Red,M (26x37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('S-R', 'Courier Bag Red,S (18x30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('XL-R', 'Courier Bag Red XL 40 x 56cm', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('R-L-P', 'Courier Bag Red (With Pocket),L (32cmx49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('R-M-P', 'Courier Bag Red (With Pocket),M (26cmx37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('R-S-P', 'Courier Bag Red (With Pocket),S (18cmx30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('R-XL-P', 'Courier Bag Red (With Pocket),XL (40cmx56cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('L-Y', 'Courier Bag Yellow,L (32x49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('M-Y', 'Courier Bag Yellow,M (26x37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('S-Y', 'Courier Bag Yellow,S (18x30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('XL-Y', 'Courier Bag Yellow XL 40 x 56cm', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('YEL-17', 'Courier Bag Yellow,17X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('YEL-20', 'Courier Bag Yellow,20X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('YEL-25', 'Courier Bag Yellow,25X35CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('YEL-28', 'Courier Bag Yellow,28X42CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('YEL-32', 'Courier Bag Yellow,32X45CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('YEL-38', 'Courier Bag Yellow,38X52CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('Y-L-P', 'Courier Bag Yellow (With Pocket),L (32cmx49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('Y-M-P', 'Courier Bag Yellow (With Pocket),M (26cmx37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('Y-S-P', 'Courier Bag Yellow (With Pocket),S (18cmx30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('Y-XL-P', 'Courier Bag Yellow (With Pocket),XL (40cmx56cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('MINT-17', 'Courier Bag Mint,17X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('MINT-20', 'Courier Bag Mint,20X30CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('MINT-25', 'Courier Bag Mint,25X35CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('MINT-28', 'Courier Bag Mint,28X42CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('MINT-32', 'Courier Bag Mint,32X45CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('MINT-38', 'Courier Bag Mint,38X52CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('XL-OR', 'Courier Bag Orange XL 40 x 56cm', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('O-L-P', 'Courier Bag Orange (With Pocket),L (32cmx49cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('O-M-P', 'Courier Bag Orange (With Pocket),M (26cmx37cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('O-S-P', 'Courier Bag Orange (With Pocket),S (18cmx30cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('O-XL-P', 'Courier Bag Orange (With Pocket),XL (40cmx56cm)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-17', 'Courier Bag White,17X30CM (40rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-20', 'Courier Bag White,20X30CM (31rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-25', 'Courier Bag White,25X35CM (23rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-28', 'Courier Bag White,28X42CM (19rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-32', 'Courier Bag White,32X45CM (10rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-35', 'Courier Bag White,35X45CM (10rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-38', 'Courier Bag White,38X52CM (8rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-40', 'Courier Bag White,40X55CM (8rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-45', 'Courier Bag White,45X55CM (10rolls/ctn)', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-55', 'Courier Bag White 55X75cm', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active'),
('W-60', 'Courier Bag White,60X80CM', 'FG', 'CourierBag', 'Purchased', 'Roll', 'Active');

-- BUBBLE WRAP (BW) SERIES (Manufactured)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('BW20CM-1', 'Bubble Wrap Single Layer Clear 20cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-2', 'Bubble Wrap Single Layer Clear 20cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-3', 'Bubble Wrap Single Layer Clear 20cm x 100m (3 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-4', 'Bubble Wrap Single Layer Clear 20cm x 100m (4 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-5', 'Bubble Wrap Single Layer Clear 20cm x 100m (5 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-BLACK-1', 'Bubble Wrap Single Layer Black 20cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-BLACK-2', 'Bubble Wrap Single Layer Black 20cm x 100m (2 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-BLACK-3', 'Bubble Wrap Single Layer Black 20cm x 100m (3 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-BLACK-4', 'Bubble Wrap Single Layer Black 20cm x 100m (4 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-BLACK-5', 'Bubble Wrap Single Layer Black 20cm x 100m (5 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-DOUBLELAYER-1', 'Bubble Wrap Double Layer Clear 20cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-DOUBLELAYER-2', 'Bubble Wrap Double Layer Clear 20cm x 100m (2 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-DOUBLELAYER-3', 'Bubble Wrap Double Layer Clear 20cm x 100m (3 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-DOUBLELAYER-4', 'Bubble Wrap Double Layer Clear 20cm x 100m (4 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW20CM-DOUBLELAYER-5', 'Bubble Wrap Double Layer Clear 20cm x 100m (5 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-1', 'Bubble Wrap Single Layer Clear 25cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-2', 'Bubble Wrap Single Layer Clear 25cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-3', 'Bubble Wrap Single Layer Clear 25cm x 100m (3 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-4', 'Bubble Wrap Single Layer Clear 25cm x 100m (4 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-BLACK-1', 'Bubble Wrap Single Layer Black 25cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-BLACK-2', 'Bubble Wrap Single Layer Black 25cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-BLACK-3', 'Bubble Wrap Single Layer Black 25cm x 100m (3 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-BLACK-4', 'Bubble Wrap Single Layer Black 25cm x 100m (4 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-BLACK-DOUBLELAYER-1', 'Bubble Wrap Double Layer Black 25cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-BLACK-DOUBLELAYER-2', 'Bubble Wrap Double Layer Black 25cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-BLACK-DOUBLELAYER-3', 'Bubble Wrap Double Layer Black 25cm x 100m (3 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-BLACK-DOUBLELAYER-4', 'Bubble Wrap Double Layer Black 25cm x 100m (4 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-DOUBLELAYER-1', 'Bubble Wrap Double Layer Clear 25cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-DOUBLELAYER-2', 'Bubble Wrap Double Layer Clear 25cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-DOUBLELAYER-3', 'Bubble Wrap Double Layer Clear 25cm x 100m (3 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW25CM-DOUBLELAYER-4', 'Bubble Wrap Double Layer Clear 25cm x 100m (4 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-1', 'Bubble Wrap Single Layer Clear 33cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-2', 'Bubble Wrap Single Layer Clear 33cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-3', 'Bubble Wrap Single Layer Clear 33cm x 100m (3 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-BLACK-1', 'Bubble Wrap Single Layer Black 33cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-BLACK-2', 'Bubble Wrap Single Layer Black 33cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-BLACK-3', 'Bubble Wrap Single Layer Black 33cm x 100m (3 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-DOUBLELAYER-1', 'Bubble Wrap Double Layer Clear 33cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-DOUBLELAYER-2', 'Bubble Wrap Double Layer Clear 33cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-DOUBLELAYER-3', 'Bubble Wrap Double Layer Clear 33cm x 100m (3 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-DOUBLELAYER-BLACK-1', 'Bubble Wrap Double Layer Black 33cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-DOUBLELAYER-BLACK-2', 'Bubble Wrap Double Layer Black 33cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW33CM-DOUBLELAYER-BLACK-3', 'Bubble Wrap Double Layer Black 33cm x 100m (3 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-BLACK', 'Bubble Wrap Single Layer Black 1m x 100m', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-BLACK-50CM-1', 'Bubble Wrap Single Layer Black 50cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-BLACK-50CM-2', 'Bubble Wrap Single Layer Black 50cm x 100m (2units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-CLEAR', 'Bubble Wrap Single Layer Clear 1m x 100m', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-CLEAR-50CM-1', 'Bubble Wrap Single Layer Clear 50cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-CLEAR-50CM-2', 'Bubble Wrap Single Layer Clear 50cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-DOUBLELAYER-50CM-1', 'Bubble Wrap Double Layer Clear 50cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-DOUBLELAYER-50CM-2', 'Bubble Wrap Double Layer Clear 50cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-DOUBLELAYER-BLACK', 'Bubble Wrap Double Layer Black 1m x 100m', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-DOUBLELAYERBLACK-50CM-1', 'Bubble Wrap Double Layer Black 50cm x 100m (1 unit)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-DOUBLELAYERBLACK-50CM-2', 'Bubble Wrap Double Layer Black 50cm x 100m (2 units)', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-DOUBLELAYER-CLEAR', 'Bubble Wrap Double Layer Clear 1m x 100m', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active'),
('BW-SV/GY', 'Bubble Wrap Single Layer Silver/Grey 1m x 100m', 'FG', 'BubbleWrap', 'Manufactured', 'Roll', 'Active');

-- TAPES (CKP/OPP) (Trading/Purchased)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('CKP-BROWNTAPE-160M', 'Cukupp Brown Tape 48MM X 180 YARD', 'FG', 'Tape', 'Purchased', 'Ctn', 'Active'),
('CKP-BROWNTAPE-80M', 'Cukupp Brown Tape 48MM X 90 YARD', 'FG', 'Tape', 'Purchased', 'Ctn', 'Active'),
('CKP-FRAGILETAPE-160M', 'Cukupp Fragile Tape 48MM X 180 YARD', 'FG', 'Tape', 'Purchased', 'Ctn', 'Active'),
('CKP-FRAGILETAPE-80M', 'Cukupp Fragile Tape 48MM X 90 YARD', 'FG', 'Tape', 'Purchased', 'Ctn', 'Active'),
('CKP-TAPECLEAR-160M', 'Cukupp Clear Tape 48MM X 180 YARD', 'FG', 'Tape', 'Purchased', 'Ctn', 'Active'),
('CKP-TAPECLEAR-80M', 'Cukupp Clear Tape 48MM X 90 YARD', 'FG', 'Tape', 'Purchased', 'Ctn', 'Active'),
('CKP-TAPECLEAR-ROLL', 'Cukupp Clear Tape 48MM X 90 YARD - ROLL', 'FG', 'Tape', 'Purchased', 'Roll', 'Active'),
('FRAGILETAPE-45-BOX', 'FRAGILE TAPE 45MM X 45MICRON X 180YARD (ROLL)', 'FG', 'Tape', 'Purchased', 'Box', 'Active'),
('FRAGILETAPE-45X45X180', 'FRAGILE TAPE 45MM X 45MICRON X 180YARD (ROLL)', 'FG', 'Tape', 'Purchased', 'Roll', 'Active'),
('OPPTAPE-C-48-BOX', 'OPP TAPE 48MM X 45MICRON X 180YARD (CLEAR)', 'FG', 'Tape', 'Purchased', 'Box', 'Active'),
('OPPTAPE-C-48X45X180', 'OPP TAPE 48MM X 45MICRON X 180YARD (CLEAR)', 'FG', 'Tape', 'Purchased', 'Roll', 'Active');

-- CUKUPP SERIES (Purchased)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('CUKUPP-B25-20PCTN', 'CUKUPP COURIER BAG 25 X 35 ( BLACK ) 20 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-B28-16PCTN', 'CUKUPP COURIER BAG 28 X 42 ( BLACK ) 16 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-B32-10PCTN', 'CUKUPP COURIER BAG 32 X 45 ( BLACK ) 10 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-B38-8PCTN', 'CUKUPP COURIER BAG 38 X 52 ( BLACK ) 8 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-B45-6PCTN', 'CUKUPP COURIER BAG 45 X 60 ( BLACK ) 6 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-B50-6PCTN', 'CUKUPP COURIER BAG 50 X 65 ( BLACK ) 6 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-B60-4PCTN', 'CUKUPP COURIER BAG 60 X 80 ( BLACK ) 4 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-GREEN17-40PCTN', 'CUKUPP COURIER BAG 17 X 30 ( GREEN ) 40 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-GREEN20-30PCTN', 'CUKUPP COURIER BAG 20 X 35 ( GREEN ) 30 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-GREEN25-20PCTN', 'CUKUPP COURIER BAG 25 X 35 ( GREEN ) 20 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-GREEN35-10PCTN', 'CUKUPP COURIER BAG 35 X 45 ( GREEN ) 10 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-GREEN40-8PCTN', 'CUKUPP COURIER BAG 40 X 55 ( GREEN ) 8 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PINK17-40PCTN', 'CUKUPP COURIER BAG 17 X 30 ( PINK ) 40 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PINK25-20PCTN', 'CUKUPP COURIER BAG 25 X 35 ( PINK ) 20 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PINK32-10PCTN', 'CUKUPP COURIER BAG 32 X 45 ( PINK ) 10 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PINK40-8PCTN', 'CUKUPP COURIER BAG 40 X 55 ( PINK ) 8 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PUR17-40PCTN', 'CUKUPP COURIER BAG 17 X 30 ( PURPLE ) 40 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PUR20-30PCTN', 'CUKUPP COURIER BAG 20 X 35 ( PURPLE ) 30 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PUR25-20PCTN', 'CUKUPP COURIER BAG 25 X 35 ( PURPLE ) 20 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PUR35-10PCTN', 'CUKUPP COURIER BAG 35 X 45 ( PURPLE ) 10 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PUR38-8PCTN', 'CUKUPP COURIER BAG 38 X 52 ( PURPLE ) 8 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-PUR40-8PCTN', 'CUKUPP COURIER BAG 40 X 55 ( PURPLE ) 8 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-W25-20PCTN', 'CUKUPP COURIER BAG 25 X 35 ( MATTE WHITE ) 20 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-W28-16PCTN', 'CUKUPP COURIER BAG 28 X 42 ( MATTE WHITE ) 16 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-W32-10PCTN', 'CUKUPP COURIER BAG 32 X 45 ( MATTE WHITE ) 10 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-W35-10PCTN', 'CUKUPP COURIER BAG 35 X 45 ( MATTE WHITE ) 10 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-W38-8PCTN', 'CUKUPP COURIER BAG 38 X 52 ( MATTE WHITE ) 8 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-W45-6PCTN', 'CUKUPP COURIER BAG 45 X 60 ( MATTE WHITE ) 6 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-W50-6PCTN', 'CUKUPP COURIER BAG 50 X 65 ( MATTE WHITE ) 6 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active'),
('CUKUPP-W60-4PCTN', 'CUKUPP COURIER BAG 60 X 80 ( MATTE WHITE ) 4 ROLLS PER CARTON', 'FG', 'CourierBag', 'Purchased', 'Ctn', 'Active');

-- STRETCH FILM (SF) (Manufactured)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('SF-22KG-BLACK', 'Stretch Film 2.2kg 200core 23Micron ( Black )', 'FG', 'StretchFilm', 'Manufactured', 'Roll', 'Active'),
('SF-22KG-CLEAR', 'Stretch Film 2.2kg 200Core 23Micron ( Clear )', 'FG', 'StretchFilm', 'Manufactured', 'Roll', 'Active'),
('SF-BLACK-SATUKOTAK6ROLL-22', 'Stretch Film 2.2kg ( Black ) ( One Carton Six Rolls )', 'FG', 'StretchFilm', 'Manufactured', 'Ctn', 'Active'),
('SF-CLEAR-SATUKOTAK6ROLL-22', 'Stretch Film 2.2kg ( Clear ) ( One Carton Six Rolls )', 'FG', 'StretchFilm', 'Manufactured', 'Ctn', 'Active'),
('SF-GREY-SATUKOTAK6ROLL-22', 'Stretch Film 2.2kg ( Silver/Grey ) ( One Carton Six Rolls )', 'FG', 'StretchFilm', 'Manufactured', 'Ctn', 'Active');

-- Raw Materials (Resin)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('LL BARU GA1820', 'LL BARU GA1820', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('LD PETRONAS N125Y', 'LD PETRONAS N125Y', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('VISTAMAX', 'VISTAMAX', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('MASTERBATCH 8092', 'MASTERBATCH 8092', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('7059', '7059', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('LLZBB', 'LLZBB', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('7050', '7050', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('LL OREN 1002AY', 'LL OREN 1002AY', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('POLYTECHS PW 60', 'POLYTECHS PW 60', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('MB BARU LAB5 250822.100', 'MB BARU LAB5 250822.100', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('HD TITAN', 'HD TITAN', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('S MERAH', 'S MERAH', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('EXXON ENABLE ( BARU )', 'EXXON ENABLE ( BARU )', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('HD LYONDELL BASE', 'HD LYONDELL BASE', 'Raw', 'Resin', 'Purchased', 'kg', 'Active'),
('RELENE', 'RELENE', 'Raw', 'Resin', 'Purchased', 'kg', 'Active');

-- Packaging (Plastic Bag)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('PLASTIC-BAG-BIRU', 'PLASTIC BAG BIRU', 'Raw', 'Bag', 'Purchased', 'Unit', 'Active'),
('PLASTIC-BAG-OREN', 'PLASTIC BAG OREN', 'Raw', 'Bag', 'Purchased', 'Unit', 'Active'),
('PLASTIC-BAG-KUNING', 'PLASTIC BAG KUNING', 'Raw', 'Bag', 'Purchased', 'Unit', 'Active'),
('PLASTIC-BAG-MERAH', 'PLASTIC BAG MERAH', 'Raw', 'Bag', 'Purchased', 'Unit', 'Active'),
('PLASTIC-BAG-HIJAU', 'PLASTIC BAG HIJAU', 'Raw', 'Bag', 'Purchased', 'Unit', 'Active'),
('PLASTIC-BAG-PLAIN', 'PLASTIC BAG PLAIN', 'Raw', 'Bag', 'Purchased', 'Unit', 'Active'),
('PLASTIC-BAG-MERAH-BARU', 'PLASTIC BAG MERAH BARU', 'Raw', 'Bag', 'Purchased', 'Unit', 'Active');

-- Packaging (Kotak)
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('KOTAK-BIASA', 'KOTAK BIASA', 'Raw', 'Packaging', 'Purchased', 'Unit', 'Active'),
('KOTAK-PACKSECURE', 'KOTAK PACKSECURE', 'Raw', 'Packaging', 'Purchased', 'Unit', 'Active'),
('KOTAK-BIRU', 'KOTAK BIRU', 'Raw', 'Packaging', 'Purchased', 'Unit', 'Active'),
('KOTAK-BABY-ROLL', 'KOTAK BABY ROLL', 'Raw', 'Packaging', 'Purchased', 'Unit', 'Active'),
('KOTAK-PACK-SECURE-2ROLL', 'KOTAK PACK SECURE (2 roll)', 'Raw', 'Packaging', 'Purchased', 'Unit', 'Active');

-- General / Spares
INSERT INTO master_items_v2 (sku, name, type, category, supply_type, uom, status) VALUES
('PAPER-ROLL', 'PAPER ROLL', 'Raw', 'Packaging', 'Purchased', 'Unit', 'Active'),
('PAPER-ROLL-BABY', 'PAPER ROLL (BABY ROLL)', 'Raw', 'Packaging', 'Purchased', 'Unit', 'Active'),
('SF-REUSE-GREY', 'STRETCH FILM GREY (Reuse/Raw)', 'Raw', 'StretchFilm', 'Purchased', 'kg', 'Active'),
('SF-REUSE-CLEAR', 'STRETCH FILM CLEAR (Reuse/Raw)', 'Raw', 'StretchFilm', 'Purchased', 'kg', 'Active'),
('SF-REUSE-BLACK', 'STRETCH FILM BLACK (Reuse/Raw)', 'Raw', 'StretchFilm', 'Purchased', 'kg', 'Active');
